In [56]:
import zipfile

import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import word_count as wc

from basic_utils import create_widget
from basic_utils import extract_logbook_data
from basic_utils import remove_undesired_columns
from IPython.display import display
from sklearn import preprocessing

## Columns needed
- speed (do all include?)
- time of year
- year
- ship name
- start point
- end point
- nationality
- wars and battles

In [27]:
logbook_data = extract_logbook_data('CLIWOC15.csv')

/Applications/miniconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2825: DtypeWarning: Columns (5,6,7,8,11,13,18,19,23,24,25,26,28,29,30,34,35,38,43,44,46,73,77,81,82,84,85,87,88,94,96,97,98,99,111,114,116,119,120,122,124,125,127,129,131,133,135,137,140) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

In [28]:
desired_columns_text=list(np.array(['VoyageFrom', 'VoyageTo', 'ShipName', 'ShipType', 
                                    'Company', 'Nationality', 'WarsAndFights', 'Year']))
undesired_columns = remove_undesired_columns(logbook_data, desired_columns_text)
data = logbook_data.drop(undesired_columns, axis=1)

In [57]:
columns = ['CargoMemo', 'LifeOnBoardMemo', 'OtherRem', 'EncRem']
key_words = ['slave',  'slaves', 'slaaf', 'slaven', 'meisjesslaaf', 'manslaaf', 'manslaven', 
            'slavenjong','jongensslaaf', 'meidslaaf', 'servant',
            'slavenmeid', 'vrouwslaaf', 'vrouwslaven', 'slavenhandel', 'slaaf',
            'esclavo', 'esclavos', 'esclave', 'esclaves']

mentions_key_words = wc.count_key_words(logbook_data, columns, key_words)
slave_index = mentions_key_words[(mentions_key_words['ContainsKeyWord'] != 0)].index

In [101]:
data = data.loc[slave_index.values]

In [102]:
data

,VoyageFrom,VoyageTo,ShipName,ShipType,Company,Nationality,Year,WarsAndFights
43039,Madeira,Accraw,Badger,Snow,RN,British,1752,0
72306,Texel,St. Eustatius,Maarsen,Oorlogsschip,ADM,Dutch,1760,0
78339,Axim,Suriname,Pollux,Fregat,MER,Dutch,1785,0
78346,Rotterdam,West Afrika,Pollux,Fregat,MER,Dutch,1785,0
78350,Axim,Suriname,Pollux,Fregat,MER,Dutch,1785,0
78351,Axim,Suriname,Pollux,Fregat,MER,Dutch,1785,0
78352,Axim,Suriname,Pollux,Fregat,MER,Dutch,1785,0
78430,NaN,NaN,Pollux,Fregat,MER,Dutch,1785,0
78447,NaN,NaN,Pollux,Fregat,MER,Dutch,1785,0
82540,Coastal Suriname,NaN,Zephyr,oorlogssnauw,ADM,Dutch,1764,0
82591,Coastal Suriname,NaN,Zephyr,oorlogssnauw,ADM,Dutch,1764,0
109767,Rio Sester,St George d'Elmina,Boreas,Fregat,ADM,Dutch,1771,0
109823,NaN,NaN,Boreas,Fregat,ADM,Dutch,1771,1
109838,Rio Sester,St George d'Elmina,Boreas,Fregat,ADM,Dutch,1771,0
109846,NaN,NaN,Boreas,Fregat,ADM,Dutch,1771,1
109859,Rio Sester,St George d'Elmina,Boreas,Fregat,ADM,Dutch,1771,0
109871,Rio Sester,St George d'Elmina,Boreas,Fregat,ADM,Dutch,1771,0
110036,West Indies,Nederland,Boreas,Fregat,ADM,Dutch,1772,0
110201,Rotterdam,Colombo,Bos en Hoven,NaN,VOC,Dutch,1760,0
114598,Batavia,Hellevoetsluis,Jerusalem,NaN,VOC,Dutch,1756,0
139078,Batavia,Rammekens,Gouverneur Generaal De Klerk,NaN,VOC,Dutch,1791,0
153256,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153257,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153258,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153296,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153297,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153298,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153299,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153300,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
153304,Middelburg,kust van Guinea en Suriname,Geertuijda en Christina,Fregat,MCC,Dutch,1785,0
...,...,...,...,...,...,...,...,...
233112,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233114,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233116,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233124,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233129,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233133,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233135,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233136,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233141,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
233164,Guinea,Suriname,Vliegende Faam,Snauw,MCC,Dutch,1771,0
243256,CÁDIZ,PACÍFICO,Na Sa DEL CARMEN (EL GRIEGO),PAQUEBOTE,NaN,Spanish,1829,0
255110,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255112,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255113,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255114,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255140,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255146,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1790,0
255253,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255266,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255268,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255269,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255278,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255280,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1790,0
255281,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1790,0
255288,Loango,Suriname,Vergenoegen,Fregat,MER,Dutch,1795,0
255290,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255294,El Mina,Suriname,Vergenoegen,Fregat,MCC,Dutch,1789,0
255425,Loango,Suriname,Vergenoegen,Fregat,MER,Dutch,1795,0
255450,Loango,Suriname,Vergenoegen,Fregat,MER,Dutch,1795,0
268544,ESTRECHO DE MAGALLANES,CÁDIZ,SANTA MARÍA DE LA CAVEZA,FRAGATA,NaN,Spanish,1786,0

In [51]:
def preprocessing_data(df_input):
    le = preprocessing.LabelEncoder()
    le.fit(df_input)
    print(list(le.classes_))
    print(len(list(le.classes_)))
    return le.transform(df_input)

In [103]:
preprocessing_data(data['VoyageFrom'].astype(str).map(lambda x: x.lower()))

['axim', 'batavia', 'braamspunt', 'coastal gulf of guinea', 'coastal suriname', 'cádiz', 'el mina', 'elmina', 'estrecho de magallanes', 'golf van guinee', 'guinea', 'guinnee (kaap axim)', 'gulf of guinea', 'ivoorkust', 'loango', 'madeira', 'malimba', 'middelburg', 'nan', 'nederland', 'netherlands', 'parimaribo', 'rio sester', 'rotterdam', 'san thomé', "st george d'elmina", 'suriname', 'texel', 'the netherlands', 'west africa', 'west afrika', 'west indies', 'west-afrika']
33

array([15, 27,  0, 23,  0,  0,  0, 18, 18,  4,  4, 22, 18, 22, 18, 22, 22,
       31, 23,  1,  1, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       17, 17, 17, 17, 17, 17, 17, 21, 17, 17, 17, 17, 17, 17, 17, 17, 17,
       18, 18, 30, 30, 17, 17, 30, 30, 30, 30, 30, 30, 17, 30, 30, 30, 30,
       30, 17, 17, 17, 17, 30, 30, 30, 30, 30, 30, 30, 30, 30,  7,  7,  7,
        2,  7,  7,  7, 18, 32, 32, 16, 29, 29, 29, 29, 29, 26, 26,  7,  7,
        7,  7,  7,  7, 30, 30, 30, 30, 19, 30, 30, 30, 30, 30, 30, 30, 30,
       10, 19, 30, 30, 30, 30, 30, 10, 10, 10, 10, 10, 10, 10, 10, 19, 10,
       11, 11, 11, 11, 11,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9, 10, 10, 10, 10, 17, 30, 30, 10, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 17, 17, 25, 24,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 19, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10,  7,  7,  7,  7, 10, 10, 10, 10, 10,  7,  7,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        7,  7, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7, 19,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, 19,  3, 12, 12, 19, 12, 12,  3,
        3,  3,  3,  3, 19,  7,  7,  7,  7, 12, 12, 12, 12, 12, 12,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 20,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7, 28, 28, 18, 28, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 14,
        6,  6, 14, 14,  8])

In [104]:
preprocessing_data(data['VoyageTo'].astype(str).map(lambda x: x.lower()))

['accraw', 'afrika', 'braamspunt', 'bramspunt', 'colombo', 'curacao', 'cádiz', 'golf van guinee', 'guinea', 'gulf of guinea', 'hellevoetsluis', 'kaap mazurado', 'kust van guinea en suriname', 'nan', 'nederland', 'pacífico', 'paramaribo', 'rammekens', 'rio berbice', 'st andries', 'st eustacius', 'st eustatius', "st george d'elmina", 'st. eustatius', 'suriname', 'vlissingen', 'west afrika']
27

array([ 0, 23, 24, 26, 24, 24, 24, 13, 13, 13, 13, 22, 13, 22, 13, 22, 22,
       14,  4, 10, 17, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12,  5, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       13, 13, 24, 24, 26, 26, 24, 24, 24, 24, 24, 24, 26, 24, 24, 24, 24,
       24, 26, 26, 26, 26, 24, 24, 24, 24, 24, 24, 24, 24, 24,  2,  2,  2,
       21,  2,  2, 24, 13,  3,  3,  3, 24, 24, 24, 24, 24, 21, 21, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 26, 24, 24, 24, 24, 24, 24, 24, 24,
       20,  8, 24, 24, 24, 24, 24, 20, 20, 20, 20, 20, 20, 20, 20,  8, 20,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 26, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 11,  1, 24, 25,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24,  8, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 16, 16, 16, 16, 16, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24,  9, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16,  9, 13, 24, 24,  9, 24, 24, 13,
       13, 13, 13, 13,  9, 16, 16, 16, 16, 24, 24, 24, 24, 24, 24, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 19, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16,  8,  7, 13,  7, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 15, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24,  6])

In [ ]:
unknown, desconocido

In [105]:
preprocessing_data(data['ShipName'].astype(str).map(lambda x: x.lower()))

['badger', 'boreas', 'bos en hoven', 'drie gesusters', 'echo', 'eenigheijt', 'geertuijda en christina', 'gouverneur generaal de klerk', 'grenadier', 'haast u langzaam', 'jerusalem', 'maarsen', 'mercurius', 'middelburgs welvaren', 'na sa del carmen (el griego)', 'nieuwe hoop', 'philadelphia', 'pollux', 'prins willem v', 'santa maría de la caveza', 'standvastigheid', 'vergenoegen', 'viegelantie', 'vliegende faam', 'vrouwe johanna cores', 'welmeenende', 'zanggodin', 'zephyr']
28

array([ 0, 11, 17, 17, 17, 17, 17, 17, 17, 27, 27,  1,  1,  1,  1,  1,  1,
        1,  2, 10,  7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  4,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15, 20,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9,  9,  9,  9, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
       22, 22, 22, 22, 22,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
       24, 24, 24, 24, 24, 24, 24, 24, 24, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 26, 26, 26, 23, 23, 23, 23, 26, 26, 26, 26, 26, 26, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
       23, 23, 14, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 19])

In [106]:
preprocessing_data(data['ShipType'].astype(str).map(lambda x: x.lower()))

['brik', 'fragata', 'fregat', 'nan', 'oorlogsschip', 'oorlogssnauw', 'paquebote', 'snauw', 'snow']
9

array([8, 4, 2, 2, 2, 2, 2, 2, 2, 5, 5, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 3, 7, 7, 3,
       3, 3, 3, 3, 7, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1])

In [107]:
preprocessing_data(data['Company'].astype(str).map(lambda x: x.lower()))

['adm', 'mcc', 'mer', 'nan', 'rn', 'voc']
6

array([4, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 2, 3])

In [108]:
preprocessing_data(data['Nationality'].map(lambda x: x.rstrip()))

['British', 'Dutch', 'Spanish']
3

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2])

## Example of preprocessing data using a fake data set

In [9]:
le = preprocessing.LabelEncoder()
le.fit(["paris", "paris", "tokyo", "amsterdam"])
list(le.classes_)
le.transform(["tokyo", "tokyo", "paris"]) 
list(le.inverse_transform([2, 2, 1]))

['tokyo', 'tokyo', 'paris']